env:
 - GHCVER=7.4.2
 - GHCVER=7.6.3
 - GHCVER=7.8.3

before_install:
 - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
 - travis_retry sudo apt-get update
 - travis_retry sudo apt-get install cabal-install-1.18 ghc-$GHCVER
 - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/1.18/bin:$HOME/.cabal/bin:$PATH
 - |
   if [ $GHCVER = "head" ] || [ ${GHCVER%.*} = "7.8" ]; then
     travis_retry sudo apt-get install happy-1.19.4 alex-3.1.3
     export PATH=/opt/alex/3.1.3/bin:/opt/happy/1.19.4/bin:$PATH
   else
     travis_retry sudo apt-get install happy alex
   fi
 - export VERSION=$(cabal info . | awk 'NR==1 { n=split($2,x,"-"); print x[n]; }')

install:
 - /bin/true

script:
 - cabal update
 - cabal install
 - cd tests
 - cabal configure --constraint="optparse-applicative < $VERSION"
 - cabal build
 - cabal install
 - cd ..
 - optparse-applicative-tests